-- liquibase formatted sql

-- changeset pgolubev:1
CREATE TABLE IF NOT EXISTS dog
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT     NOT NULL,
    age                    INT,
    breed                  TEXT     NOT NULL
);

CREATE TABLE IF NOT EXISTS owner
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT     NOT NULL,
    phoneNumber            INT NOT NULL,
    chatId                 BIGINT NOT NULL
)